import type { MacroMetric } from './types';

// Static macro metrics — values sourced from official central bank / statistical office releases.
// Last updated: April 2026. Override by calendar enrichment when actuals are available.
export const macroMetrics: MacroMetric[] = [
  {
    id: 'USD',
    countryName: 'United States',
    flag: '🇺🇸',
    interestRate: {
      value: '3.75%',
      period: 'Mar 2026',
      trend: 'down',
      source: 'Federal Reserve',
      lastUpdated: '2026-03',
    },
    inflation: {
      value: '3.3%',
      period: 'Mar 2026 YoY',
      trend: 'up',
      source: 'BLS CPI',
      lastUpdated: '2026-04',
    },
    unemployment: {
      value: '4.3%',
      period: 'Mar 2026',
      trend: 'up',
      source: 'BLS',
      lastUpdated: '2026-04',
    },
    gdpGrowth: {
      value: '+0.5%',
      period: 'Q1 2026 Adv.',
      trend: 'down',
      source: 'BEA',
      lastUpdated: '2026-04',
    },
  },
  {
    id: 'EUR',
    countryName: 'Germany',
    flag: '🇩🇪',
    interestRate: {
      value: '2.15%',
      period: 'Mar 2026',
      trend: 'down',
      source: 'ECB Deposit Rate',
      lastUpdated: '2026-03',
    },
    inflation: {
      value: '2.2%',
      period: 'Mar 2026 YoY',
      trend: 'up',
      source: 'Destatis CPI',
      lastUpdated: '2026-04',
    },
    unemployment: {
      value: '6.3%',
      period: 'Mar 2026',
      trend: 'up',
      source: 'Destatis',
      lastUpdated: '2026-04',
    },
    gdpGrowth: {
      value: '+0.2%',
      period: 'Q4 2025 q/q',
      trend: 'up',
      source: 'Destatis',
      lastUpdated: '2026-02',
    },
  },
  {
    id: 'GBP',
    countryName: 'United Kingdom',
    flag: '🇬🇧',
    interestRate: {
      value: '3.75%',
      period: 'Mar 2026',
      trend: 'down',
      source: 'Bank of England',
      lastUpdated: '2026-03',
    },
    inflation: {
      value: '3.3%',
      period: 'Mar 2026 YoY',
      trend: 'up',
      source: 'ONS CPI',
      lastUpdated: '2026-04',
    },
    unemployment: {
      value: '4.9%',
      period: 'Feb 2026',
      trend: 'up',
      source: 'ONS',
      lastUpdated: '2026-04',
    },
    gdpGrowth: {
      value: '+0.1%',
      period: 'Q4 2025 q/q',
      trend: 'down',
      source: 'ONS',
      lastUpdated: '2026-02',
    },
  },
  {
    id: 'JPY',
    countryName: 'Japan',
    flag: '🇯🇵',
    interestRate: {
      value: '0.75%',
      period: 'Jan 2026',
      trend: 'up',
      source: 'Bank of Japan',
      lastUpdated: '2026-01',
    },
    inflation: {
      value: '1.5%',
      period: 'Mar 2026 YoY',
      trend: 'down',
      source: 'MIC CPI',
      lastUpdated: '2026-04',
    },
    unemployment: {
      value: '2.6%',
      period: 'Feb 2026',
      trend: 'up',
      source: 'MIC',
      lastUpdated: '2026-04',
    },
    gdpGrowth: {
      value: '+0.3%',
      period: 'Q4 2025 q/q',
      trend: 'up',
      source: 'Cabinet Office',
      lastUpdated: '2026-02',
    },
  },
  {
    id: 'CAD',
    countryName: 'Canada',
    flag: '🇨🇦',
    interestRate: {
      value: '2.25%',
      period: 'Mar 2026',
      trend: 'down',
      source: 'Bank of Canada',
      lastUpdated: '2026-03',
    },
    inflation: {
      value: '2.4%',
      period: 'Mar 2026 YoY',
      trend: 'up',
      source: 'Statistics Canada CPI',
      lastUpdated: '2026-04',
    },
    unemployment: {
      value: '6.7%',
      period: 'Mar 2026',
      trend: 'flat',
      source: 'Statistics Canada',
      lastUpdated: '2026-04',
    },
    gdpGrowth: {
      value: '-0.2%',
      period: 'Feb 2026 m/m',
      trend: 'down',
      source: 'Statistics Canada',
      lastUpdated: '2026-04',
    },
  },
  {
    id: 'AUD',
    countryName: 'Australia',
    flag: '🇦🇺',
    interestRate: {
      value: '4.10%',
      period: 'Feb 2026',
      trend: 'down',
      source: 'Reserve Bank of Australia',
      lastUpdated: '2026-02',
    },
    inflation: {
      value: '3.7%',
      period: 'Q4 2025 YoY',
      trend: 'up',
      source: 'ABS CPI',
      lastUpdated: '2026-01',
    },
    unemployment: {
      value: '4.3%',
      period: 'Mar 2026',
      trend: 'up',
      source: 'ABS',
      lastUpdated: '2026-04',
    },
    gdpGrowth: {
      value: '+0.8%',
      period: 'Q3 2025 q/q',
      trend: 'flat',
      source: 'ABS',
      lastUpdated: '2025-12',
    },
  },
];
