import type { MacroMetric } from './types';

// Static macro metrics — values sourced from official central bank / statistical office releases.
// Update these manually or wire up a future API integration.
export const macroMetrics: MacroMetric[] = [
  {
    id: 'USD',
    countryName: 'United States',
    flag: '🇺🇸',
    interestRate: {
      value: '4.25–4.50%',
      period: 'Dec 2024',
      trend: 'down',
      source: 'Federal Reserve',
      lastUpdated: '2024-12',
    },
    inflation: {
      value: '2.9%',
      period: 'Dec 2024 YoY',
      trend: 'flat',
      source: 'BLS CPI',
      lastUpdated: '2025-01',
    },
    unemployment: {
      value: '4.1%',
      period: 'Dec 2024',
      trend: 'flat',
      source: 'BLS',
      lastUpdated: '2025-01',
    },
    gdpGrowth: {
      value: '+3.1%',
      period: 'Q3 2024 Ann.',
      trend: 'up',
      source: 'BEA',
      lastUpdated: '2024-12',
    },
  },
  {
    id: 'EUR',
    countryName: 'Eurozone',
    flag: '🇪🇺',
    interestRate: {
      value: '3.00%',
      period: 'Dec 2024',
      trend: 'down',
      source: 'ECB Deposit Rate',
      lastUpdated: '2024-12',
    },
    inflation: {
      value: '2.4%',
      period: 'Dec 2024 YoY',
      trend: 'flat',
      source: 'Eurostat HICP',
      lastUpdated: '2025-01',
    },
    unemployment: {
      value: '6.3%',
      period: 'Nov 2024',
      trend: 'flat',
      source: 'Eurostat',
      lastUpdated: '2025-01',
    },
    gdpGrowth: {
      value: '+0.9%',
      period: 'Q3 2024 YoY',
      trend: 'up',
      source: 'Eurostat',
      lastUpdated: '2024-10',
    },
  },
  {
    id: 'GBP',
    countryName: 'United Kingdom',
    flag: '🇬🇧',
    interestRate: {
      value: '4.75%',
      period: 'Dec 2024',
      trend: 'down',
      source: 'Bank of England',
      lastUpdated: '2024-12',
    },
    inflation: {
      value: '2.5%',
      period: 'Dec 2024 YoY',
      trend: 'up',
      source: 'ONS CPI',
      lastUpdated: '2025-01',
    },
    unemployment: {
      value: '4.4%',
      period: 'Nov 2024',
      trend: 'up',
      source: 'ONS',
      lastUpdated: '2025-01',
    },
    gdpGrowth: {
      value: '+1.0%',
      period: 'Q3 2024 YoY',
      trend: 'up',
      source: 'ONS',
      lastUpdated: '2024-10',
    },
  },
  {
    id: 'JPY',
    countryName: 'Japan',
    flag: '🇯🇵',
    interestRate: {
      value: '0.25%',
      period: 'Jul 2024',
      trend: 'up',
      source: 'Bank of Japan',
      lastUpdated: '2024-07',
    },
    inflation: {
      value: '3.6%',
      period: 'Dec 2024 YoY',
      trend: 'up',
      source: 'MIC CPI',
      lastUpdated: '2025-01',
    },
    unemployment: {
      value: '2.4%',
      period: 'Nov 2024',
      trend: 'flat',
      source: 'MIC',
      lastUpdated: '2025-01',
    },
    gdpGrowth: {
      value: '-0.9%',
      period: 'Q3 2024 Ann.',
      trend: 'down',
      source: 'Cabinet Office',
      lastUpdated: '2024-11',
    },
  },
  {
    id: 'CAD',
    countryName: 'Canada',
    flag: '🇨🇦',
    interestRate: {
      value: '3.25%',
      period: 'Dec 2024',
      trend: 'down',
      source: 'Bank of Canada',
      lastUpdated: '2024-12',
    },
    inflation: {
      value: '1.8%',
      period: 'Nov 2024 YoY',
      trend: 'down',
      source: 'Statistics Canada CPI',
      lastUpdated: '2024-12',
    },
    unemployment: {
      value: '6.8%',
      period: 'Nov 2024',
      trend: 'up',
      source: 'Statistics Canada',
      lastUpdated: '2024-12',
    },
    gdpGrowth: {
      value: '+1.0%',
      period: 'Q3 2024 Ann.',
      trend: 'flat',
      source: 'Statistics Canada',
      lastUpdated: '2024-11',
    },
  },
  {
    id: 'AUD',
    countryName: 'Australia',
    flag: '🇦🇺',
    interestRate: {
      value: '4.35%',
      period: 'Nov 2024',
      trend: 'flat',
      source: 'Reserve Bank of Australia',
      lastUpdated: '2024-11',
    },
    inflation: {
      value: '2.8%',
      period: 'Q3 2024 YoY',
      trend: 'down',
      source: 'ABS CPI',
      lastUpdated: '2024-10',
    },
    unemployment: {
      value: '3.9%',
      period: 'Nov 2024',
      trend: 'flat',
      source: 'ABS',
      lastUpdated: '2024-12',
    },
    gdpGrowth: {
      value: '+0.8%',
      period: 'Q3 2024 YoY',
      trend: 'down',
      source: 'ABS',
      lastUpdated: '2024-11',
    },
  },
];
